-- TABELA DE USUÁRIOS
CREATE TABLE IF NOT EXISTS usuarios (
  id SERIAL PRIMARY KEY,
  login VARCHAR(50) UNIQUE NOT NULL,
  senha_hash VARCHAR(255) NOT NULL
);

-- TABELA DE MÚSICAS
CREATE TABLE IF NOT EXISTS musicas (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  artista VARCHAR(255) NOT NULL,
  audio_url TEXT NOT NULL,
  capa_url TEXT,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

