-- 1. APAGAR AS TABELAS ANTIGAS PARA LIMPAR O ERRO
DROP TABLE IF EXISTS usuarios;
DROP TABLE IF EXISTS musicas;

-- 2. CRIAR A TABELA DE USUÁRIOS COM O NOME CORRETO (senha)
CREATE TABLE usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  login VARCHAR(50) UNIQUE NOT NULL,
  senha VARCHAR(255) NOT NULL
);

-- 3. CRIAR A TABELA DE MÚSICAS
CREATE TABLE musicas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  artista VARCHAR(255) NOT NULL,
  audio_url TEXT NOT NULL,
  capa_url TEXT,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. AGORA SIM, INSERIR O USUÁRIO ADMIN
INSERT INTO usuarios (login, senha) 
VALUES ('admin', '$2a$10$76YmP1N.R1.f7.G.tMvYueP/3mI0ZlGvD5.N7K0Z1p2O3m4n5o6p7');